version: '3.8'

services:
  my_project:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    container_name: ${CONTAINER_NAME}
    # Add other configurations as needed, like:
    ports:
      - "8888:8888"
    volumes:
      - ../:/${PROJECT_NAME}
    # environment:
    #   - ENV_VAR=value
